config/routes.rb
Maxprog::Application.routes.draw do
  resources :posts

  resources :docentes

  resources :escuelas

  resources :provis

  get "home/index"

  root :to  => 'home#index'
  match '/' => "home#index", :as => :home

  match 'project'        => 'project#index'
  match 'listaesc'       => 'escuelas#listaesc'

  match '/posts/:id/code' => 'posts#show_code', :as => 'show_code'

end

app/models/escuela.rb
class Escuela < ActiveRecord::Base
  attr_accessible :institu, :provi_id

  validates :institu, :presence => true
  validates :provi_id, :presence => true

  belongs_to :provi, :inverse_of => :escuelas
  has_many :docentes, :through => :posts
  has_many :posts
end

app/controllers/escuelas_controller.rb
class EscuelasController < ApplicationController
  # GET /escuelas
  # GET /escuelas.json
  def index
    @escuelas = Escuela.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @escuelas }
    end
  end


  def listaesc
    @escuelas = Escuela.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @escuelas }
    end
  end


  # GET /escuelas/1
  # GET /escuelas/1.json
  def show
    @escuela = Escuela.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @escuela }
    end
  end

  # GET /escuelas/new
  # GET /escuelas/new.json
  def new
    @escuela = Escuela.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @escuela }
    end
  end

  # GET /escuelas/1/edit
  def edit
    @escuela = Escuela.find(params[:id])
  end

  # POST /escuelas
  # POST /escuelas.json
  def create
    @escuela = Escuela.new(params[:escuela])

    respond_to do |format|
      if @escuela.save
        format.html { redirect_to @escuela, notice: 'Escuela was successfully created.' }
        format.json { render json: @escuela, status: :created, location: @escuela }
      else
        format.html { render action: "new" }
        format.json { render json: @escuela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /escuelas/1
  # PUT /escuelas/1.json
  def update
    @escuela = Escuela.find(params[:id])

    respond_to do |format|
      if @escuela.update_attributes(params[:escuela])
        format.html { redirect_to @escuela, notice: 'Escuela was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @escuela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escuelas/1
  # DELETE /escuelas/1.json
  def destroy
    @escuela = Escuela.find(params[:id])
    @escuela.destroy

    respond_to do |format|
      format.html { redirect_to escuelas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/escuelas_helper.rb
module EscuelasHelper
end

app/views/escuelas/_form.html.erb
<%= form_for(@escuela) do |f| %>
  <% if @escuela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@escuela.errors.count, "error") %> prohibited this escuela from being saved:</h2>

      <ul>
      <% @escuela.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <tr class="field">
    <td><%= f.label :institu %></td>
    <td><%= f.text_field :institu %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :provi_id %></td>
    <td><%= f.select( :provi_id, options_for_select( Provi.all.map { |p| [p.prov, p.id] } ) ) %></td>
  </tr>

  <tr class="actions">
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>
<% end %>

app/views/escuelas/edit.html.erb
<div class="container">
<div class="well">

<h1>Editar escuela</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @escuela %> |
<%= link_to 'Volver', escuelas_path %>

</div>
</div>

app/views/escuelas/index.html.erb
<div class="container">
  <div class="well">
    <h1>Listado de escuelas</h1>
    <table class="table">
      <tr>
        <th>Id</th>
        <th>Institu</th>
        <th>IdProvi</th>
        <th>Prov</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @escuelas.each do |escuela| %>
      <tr>
        <td><%= escuela.id %></td>
        <td><%= escuela.institu %></td>
        <td><%= escuela.provi_id %></td>
        <td><%= escuela.provi.prov %></td>
        <td><%= link_to 'Mostrar', escuela %></td>
        <td><%= link_to 'Editar', edit_escuela_path(escuela) %></td>
        <td><%= link_to 'Eliminar', escuela, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
      <% end %>
    </table>
    <br />
    <%= link_to 'Nueva escuela', new_escuela_path %>
  </div>
  <div class="well">
    <h3>Gestión del proyecto</h3>
    <div> <%= link_to "Gestionar Provincias", provis_path %> </div>
    <div> <%= link_to "Gestionar Escuelas", escuelas_path %> </div>
    <div> <%= link_to "Gestionar Docentes", docentes_path %> </div>
    <div> <%= link_to "Gestionar Obras", posts_path %> </div>
  </div>
</div>

app/views/escuelas/listaesc.html.erb
<div class="container">
<div class="well">

<h3>Las escuelas del proyecto</h3>
<table class="table">
  <tr>
    <th>#</th>
    <th>Institución</th>
    <!--   <th>IdProvi</th> -->
    <th>Provincia</th>
    <th>Enlace</th>
    <th> </th>
  </tr>

<% @escuelas.each do |escuela| %>
  <tr>
    <td><%= escuela.id %></td>
    <td><%= escuela.institu %></td>
    <!-- <td><%= escuela.provi_id %></td> -->
    <td><%= escuela.provi.prov %></td>
    <td> <div class="btn btn-info"> Ver obras </div> </td>
    <td>  </td>
 
  </tr>
<% end %>
</table>

</div>
</div>


<% @posts = Post.where(:escuela_id => 3) %>
<% @posts.each do |post| %>
<p>
  <b>Obra:</b>
  <%= post.obra %>
</p>

<p>
  <b>Autor1:</b>
  <%= post.autor1 %>
</p>

<p>
  <b>Autor2:</b>
  <%= post.autor2 %>
</p>

<p>
  <b>Autor3:</b>
  <%= post.autor3 %>
</p>

<p>
  <b>Autor4:</b>
  <%= post.autor4 %>
</p>

<p>
  <b>Fecha:</b>
  <%= post.fecha %>
</p>

<p>
  <b>File:</b>
  <%= post.file %>
</p>

<p>
  <b>Codigo:</b>
  <%= post.codigo %>
</p>

<p>
  <b>Escuela:</b>
  <%= post.escuela_id %>
</p>

<p>
  <b>Curso:</b>
  <%= post.curso %>
</p>

<p>
  <b>Docente:</b>
  <%= post.docente_id %>
</p>
<% end %>

app/views/escuelas/new.html.erb
<div class="container">
<div class="well">

<h3>Agregar escuela</h3>

<%= render 'form' %>

<%= link_to 'Volver', escuelas_path %>

</div>
</div>

app/views/escuelas/show.html.erb
<div class="container">
<div class="well">

<p id="notice"><%= notice %></p>

<p>
  <b>Institu:</b>
  <%= @escuela.institu %>
</p>

<p>
  <b>Provi:</b>
  <%= @escuela.provi_id %>
</p>


<%= link_to 'Editar', edit_escuela_path(@escuela) %> |
<%= link_to 'Volver', escuelas_path %>

</div>
</div>