config/routes.rb
Maxprog::Application.routes.draw do
  resources :posts

  resources :docentes

  resources :escuelas

  resources :provis

  get "home/index"

  root :to  => 'home#index'
  match '/' => "home#index", :as => :home

  match 'project'        => 'project#index'
  match 'listaesc'       => 'escuelas#listaesc'

  match '/posts/:id/code' => 'posts#show_code', :as => 'show_code'

end

app/models/docente.rb
class Docente < ActiveRecord::Base
  attr_accessible :name, :pass, :user
  
  validates :name,  :presence => true
  validates :pass, :presence => true
  validates :user, :presence => true

  has_many :posts
  has_many :escuelas, :through => :posts
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  # GET /docentes
  # GET /docentes.json
  def index
    @docentes = Docente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docentes }
    end
  end

  # GET /docentes/1
  # GET /docentes/1.json
  def show
    @docente = Docente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @docente }
    end
  end

  # GET /docentes/new
  # GET /docentes/new.json
  def new
    @docente = Docente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @docente }
    end
  end

  # GET /docentes/1/edit
  def edit
    @docente = Docente.find(params[:id])
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.new(params[:docente])

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: 'Docente was successfully created.' }
        format.json { render json: @docente, status: :created, location: @docente }
      else
        format.html { render action: "new" }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /docentes/1
  # PUT /docentes/1.json
  def update
    @docente = Docente.find(params[:id])

    respond_to do |format|
      if @docente.update_attributes(params[:docente])
        format.html { redirect_to @docente, notice: 'Docente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente = Docente.find(params[:id])
    @docente.destroy

    respond_to do |format|
      format.html { redirect_to docentes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@docente.errors.count, "error") %> prohibited this docente from being saved:</h2>

      <ul>
      <% @docente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <tr class="field">
    <td><%= f.label :user %></td>
    <td><%= f.text_field :user %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :pass %></td>
    <td><%= f.text_field :pass %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr class="actions">
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>
<% end %>

app/views/docentes/edit.html.erb
<div class="container">
<div class="well">

<h1>Editar docente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @docente %> |
<%= link_to 'Volver', docentes_path %>

</div>
</div>

app/views/docentes/index.html.erb
<div class="container">
<div class="well">

<h1>Listado de docentes</h1>

<table class="table">
  <tr>
    <th>Id</th>
    <th>User</th>
    <th>Pass</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docentes.each do |docente| %>
  <tr>
    <td><%= docente.id %></td>
    <td><%= docente.user %></td>
    <td><%= docente.pass %></td>
    <td><%= docente.name %></td>
    <td><%= link_to 'Mostrar', docente %></td>
    <td><%= link_to 'Editar', edit_docente_path(docente) %></td>
    <td><%= link_to 'Eliminar', docente, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo docente', new_docente_path %>

</div>


  <div class="well">
    <h3>Gestión del proyecto</h3>
    <div> <%= link_to "Gestionar Provincias", provis_path %> </div>
    <div> <%= link_to "Gestionar Escuelas", escuelas_path %> </div>
    <div> <%= link_to "Gestionar Docentes", docentes_path %> </div>
    <div> <%= link_to "Gestionar Obras", posts_path %> </div>
  </div>

</div>

app/views/docentes/new.html.erb
<div class="container">
<div class="well">

<h3>Agregar docente</h3>

<%= render 'form' %>

<%= link_to 'Volver', docentes_path %>

</div>
</div>

app/views/docentes/show.html.erb
<div class="container">
<div class="well">

<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @docente.user %>
</p>

<p>
  <b>Pass:</b>
  <%= @docente.pass %>
</p>

<p>
  <b>Name:</b>
  <%= @docente.name %>
</p>


<%= link_to 'Editar', edit_docente_path(@docente) %> |
<%= link_to 'Volver', docentes_path %>

</div>
</div>