config/routes.rb
Maxprog::Application.routes.draw do
  resources :posts

  resources :docentes

  resources :escuelas

  resources :provis

  get "home/index"

  root :to  => 'home#index'
  match '/' => "home#index", :as => :home

  match 'project'        => 'project#index'
  match 'listaesc'       => 'escuelas#listaesc'

  match '/posts/:id/code' => 'posts#show_code', :as => 'show_code'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :autor1, :autor2, :autor3, :autor4, :codigo, :docente_id, :escuela_id, :fecha, :file, :obra, :curso, :comentario

  validates :autor1, :presence => true
  validates :codigo, :presence => true
  validates :docente_id, :presence => true
  validates :escuela_id, :presence => true
  validates :fecha, :presence => true
  validates :obra, :presence => true

  belongs_to :docente, :inverse_of => :posts
  belongs_to :escuela, :inverse_of => :posts
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def show_code
    code = '';
    if post = Post.find(params[:id])
      code = post.codigo
    end
    render :text => code
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <tr class="field">
    <td><%= f.label :obra %></td>
    <td><%= f.text_field :obra %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :autor1 %></td>
    <td><%= f.text_field :autor1 %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :autor2 %></td>
    <td><%= f.text_field :autor2 %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :autor3 %></td>
    <td><%= f.text_field :autor3 %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :autor4 %></td>
    <td><%= f.text_field :autor4 %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :fecha %></td>
    <td><%= f.date_select :fecha %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :codigo %></td>
    <td><%= f.text_area :codigo %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :escuela_id %></td>
    <td><%= f.select( :escuela_id, options_for_select( Escuela.all.map { |e| [e.institu, e.id] } ) ) %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :curso %></td>
    <td><%= f.text_field :curso %></td>
  </tr>
  <tr class="field">
    <td><%= f.label :docente_id %></td>
    <td><%= f.select( :docente_id, options_for_select( Docente.all.map { |d| [d.name, d.id] } ) ) %></td>
  <tr class="field">
    <td><%= f.label :comentario %></td>
    <td><%= f.text_area :comentario %></td>
  </tr>
  <tr class="actions">
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>

<% end %>

app/views/posts/_listadoc.erb
<table>
<% @docentes = Docente.all %>
<% @docentes.each do |docente| %>
  <tr>
    <td><%= docente.id %></td>
    <td><%= docente.name %></td>
  </tr>
<% end %>
</table>

app/views/posts/_listaesc.html.erb
<table>
<% @escuelas = Escuela.all %>
<% @escuelas.each do |escuela| %>
  <tr>
    <td><%= escuela.id %></td>
    <td><%= escuela.institu %></td>
  </tr>
<% end %>
</table>

app/views/posts/edit.html.erb
<div class="container">
<div class="well">

<h1>Editar obra</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @post %> |
<%= link_to 'Volver', posts_path %>

</div>
</div>

app/views/posts/index.html.erb
<div class="container">
<div class="well">

<h1>Listado de obras</h1>

<table class="table">
  <tr>
    <th>Id</th>
    <th>Obra</th>
    <th>Autor1</th>
    <th>Autor2</th>
    <th>Autor3</th>
    <th>Autor4</th>
    <th>Fecha</th>
    <th>EscuelaId</th>
    <th>Escuela</th>
    <th>Curso</th>
    <th>Provincia</th>
    <th>DocenteId</th>
    <th>Docente</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.obra %></td>
    <td><%= post.autor1 %></td>
    <td><%= post.autor2 %></td>
    <td><%= post.autor3 %></td>
    <td><%= post.autor4 %></td>
    <td><%= post.fecha %></td>
    <td><%= post.escuela_id %></td>
    <td><%= post.escuela.institu %></td>
    <td><%= post.curso %></td>
    <td><%= post.escuela.provi.prov %></td>
    <td><%= post.docente_id %></td>
    <td><%= post.docente.name %></td>
    <td><%= link_to 'Mostrar', post %></td>
    <td><%= link_to 'Editar', edit_post_path(post) %></td>
    <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva obra', new_post_path %>

</div>

<div class="well">
  <h3>Gestión del proyecto</h3>
  <div> <%= link_to "Gestionar Provincias", provis_path %> </div>
  <div> <%= link_to "Gestionar Escuelas", escuelas_path %> </div>
  <div> <%= link_to "Gestionar Docentes", docentes_path %> </div>
  <div> <%= link_to "Gestionar Obras", posts_path %> </div>
</div>

</div>

app/views/posts/new.html.erb
<div class="container">
<div class="well">

<h3>Nueva obra</h3>

<%= render 'form' %>

<%= link_to 'Volver', posts_path %>

</div>
</div>

app/views/posts/postesc.html.erb
<% @posts.each do |post| %>
<p>
  <b>Obra:</b>
  <%= post.obra %>
</p>

<p>
  <b>Autor1:</b>
  <%= post.autor1 %>
</p>

<p>
  <b>Autor2:</b>
  <%= post.autor2 %>
</p>

<p>
  <b>Autor3:</b>
  <%= post.autor3 %>
</p>

<p>
  <b>Autor4:</b>
  <%= post.autor4 %>
</p>

<p>
  <b>Fecha:</b>
  <%= post.fecha %>
</p>

<p>
  <b>File:</b>
  <%= post.file %>
</p>

<p>
  <b>Codigo:</b>
  <%= post.codigo %>
</p>

<p>
  <b>Escuela:</b>
  <%= post.escuela_id %>
</p>

<p>
  <b>Curso:</b>
  <%= post.curso %>
</p>

<p>
  <b>Docente:</b>
  <%= post.docente_id %>
</p>


<% end %>

app/views/posts/show.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">La Obra</a></li>
    <li><a href="#tab2" data-toggle="tab">El Código</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <p>
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span4">
              <h3> <%= @post.obra %> </h3>
              <p>Autores: <%= @post.autor1 %> <%= @post.autor2 %> <%= @post.autor3 %> <%= @post.autor4 %></p>
              <p>Escuela: <%= @post.escuela.institu %> </p>
              <p>Curso: <%= @post.curso %> </p>
              <p>Año: <%= @post.fecha.year %></p>
              <p>Docente: <%= @post.docente.name %></p>
              <p>Provincia: <%= @post.escuela.provi.prov %> </p>
              <p>Fecha de creación: <%= @post.fecha %></p>
              <p>Inventario: <%= @post.id %></p>
              <p>Comentario: <%= @post.comentario %></p>
            </div>
            <div class="span8">
               <canvas data-processing-sources="<%= show_code_path(@post.id) %>"></canvas>
            </div>
          </div>
        </div>
      </p>
    </div>
    <div class="tab-pane" id="tab2">
      <p>
        <div class="container-fluid">
          <div class="row-fluid">
            <div class="span4">
              <h3> <%= @post.obra %> </h3>
              <p>Autores: <%= @post.autor1 %> <%= @post.autor2 %> <%= @post.autor3 %> <%= @post.autor4 %></p>
              <p>Escuela: <%= @post.escuela.institu %> </p>
              <p>Curso: <%= @post.curso %> </p>
              <p>Año: <%= @post.fecha.year %></p>
              <p>Docente: <%= @post.docente.name %></p>
              <p>Provincia: <%= @post.escuela.provi.prov %> </p>
              <p>Fecha de creación: <%= @post.fecha %></p>
              <p>Inventario: <%= @post.id %></p>
            </div>
            <div class="span8">
              <!-- ACA EL CODIGO -->
              <pre class="prettyprint lang-java"><%= @post.codigo %></pre>
            </div>
          </div>
        </div>
      </p>
    </div>
  </div>
</div>