config/routes.rb
Maxprog::Application.routes.draw do
  resources :posts

  resources :docentes

  resources :escuelas

  resources :provis

  get "home/index"

  root :to  => 'home#index'
  match '/' => "home#index", :as => :home

  match 'project'        => 'project#index'
  match 'listaesc'       => 'escuelas#listaesc'

  match '/posts/:id/code' => 'posts#show_code', :as => 'show_code'

end

app/models/provi.rb
class Provi < ActiveRecord::Base
  attr_accessible :prov

  validates :prov, :presence => true

  has_many :escuelas, :inverse_of => :provi
end

app/controllers/provis_controller.rb
class ProvisController < ApplicationController
  # GET /provis
  # GET /provis.json
  def index
    @provis = Provi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @provis }
    end
  end

  # GET /provis/1
  # GET /provis/1.json
  def show
    @provi = Provi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provi }
    end
  end

  # GET /provis/new
  # GET /provis/new.json
  def new
    @provi = Provi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provi }
    end
  end

  # GET /provis/1/edit
  def edit
    @provi = Provi.find(params[:id])
  end

  # POST /provis
  # POST /provis.json
  def create
    @provi = Provi.new(params[:provi])

    respond_to do |format|
      if @provi.save
        format.html { redirect_to @provi, notice: 'Provi was successfully created.' }
        format.json { render json: @provi, status: :created, location: @provi }
      else
        format.html { render action: "new" }
        format.json { render json: @provi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /provis/1
  # PUT /provis/1.json
  def update
    @provi = Provi.find(params[:id])

    respond_to do |format|
      if @provi.update_attributes(params[:provi])
        format.html { redirect_to @provi, notice: 'Provi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provis/1
  # DELETE /provis/1.json
  def destroy
    @provi = Provi.find(params[:id])
    @provi.destroy

    respond_to do |format|
      format.html { redirect_to provis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/provis_helper.rb
module ProvisHelper
end

app/views/provis/_form.html.erb
<%= form_for(@provi) do |f| %>
  <% if @provi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provi.errors.count, "error") %> prohibited this provi from being saved:</h2>

      <ul>
      <% @provi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
  <tr class="field">
    <td><%= f.label :prov %></td>
    <td><%= f.text_field :prov %></td>
  </tr>
  <tr class="actions">
    <td><%= f.submit %></td>
    <td></td>
  </tr>
</table>
<% end %>

app/views/provis/edit.html.erb
<div class="container">
<div class="well">

<h1>Editar provincia</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @provi %> |
<%= link_to 'Volver', provis_path %>

</div>
</div>

app/views/provis/index.html.erb
<div class="container">
<div class="well">

<h1>Listado de provincias</h1>

<table class="table">
  <tr>
    <th>Id</th>
    <th>Prov</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @provis.each do |provi| %>
  <tr>
    <td><%= provi.id %></td>
    <td><%= provi.prov %></td>
    <td><%= link_to 'Mostrar', provi %></td>
    <td><%= link_to 'Editar', edit_provi_path(provi) %></td>
    <td><%= link_to 'Eliminar', provi, method: :delete, data: { confirm: '¿Está seguro' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva provincia', new_provi_path %>

</div>

<div class="well">
  <h3>Gestión del proyecto</h3>
  <div> <%= link_to "Gestionar Provincias", provis_path %> </div>
  <div> <%= link_to "Gestionar Escuelas", escuelas_path %> </div>
  <div> <%= link_to "Gestionar Docentes", docentes_path %> </div>
  <div> <%= link_to "Gestionar Obras", posts_path %> </div>
</div>
</div>

app/views/provis/new.html.erb
<div class="container">
<div class="well">

<h3>Agregar provincia</h3>

<%= render 'form' %>

<%= link_to 'Volver', provis_path %>

</div>
</div>

app/views/provis/show.html.erb
<div class="container">
<div class="well">

<p id="notice"><%= notice %></p>

<p>
  <b>Prov:</b>
  <%= @provi.prov %>
</p>


<%= link_to 'Editar', edit_provi_path(@provi) %> |
<%= link_to 'Volver', provis_path %>

</div>
</div>